/*
 * File: mtable.js, created by Peter Welby 18 Oct. 2015
 * This script implements the single-page application functionality
 * which reads form input and synchronizes it with the location hash
 * to facilitate back/forward functionality, bookmarking and sharing
 * created tables, etc.
 */

"use strict";

/** Validation function -- checks to make sure inputs are filled in and ordered correctly,
 *  i.e. "start" is smaller than "end". If all the inputs are valid, they end up in the
 *  inputVals array for the purposes of generating the multiplication table.*/
var validate = function() {
    console.log("I got called!");
    var i,
        bFormIsValid = true;

    for (i = 0; i < 4; i++) {
        // check for blank fields
        if ($("#in" + (i + 1)).val() == "") {
            bFormIsValid = false;
            $("#in" + (i + 1)).css("background-color", "rgba(255, 0, 0, 0.5)");
            $("#message").text("Please fill out all fields before generating a table.");
        // check to make sure the Start of the range is not bigger than the End
        } else if ($("#in" + (i + 1)).attr("class") === "startInput" &&
                   $("#in" + (i + 2)).val() < $("#in" + (i + 1)).val()) {
            bFormIsValid = false;
            $("#in" + (i + 1)).css("background-color", "rgba(255, 0, 0, 0.5)");
            $("#in" + (i + 2)).css("background-color", "rgba(255, 0, 0, 0.5)");
            $("#message").text("Cannot generate table -- Start cannot be greater than End");
        } else {
            $("#in" + (i + 1)).css("background-color", "initial");
        }
    }
    if (bFormIsValid) {
        $("#message").text("");
    }
    return bFormIsValid;
};

/** Parse the search string generated by the form submission */
var parseSearchString = function() {
    var i, objValues = {},
        arrSearchSplit = location.search.substr(1).split("&").split("=");

    for (i = 0; i < arrSearchSplit.length; i += 2) {
        objValues[arrSearchSplit[i]] = Number(arrSearchSplit[i + 1]);
    }

    return objValues;
};

/** Generate the table, as long as the bFormIsValid flag is set. */
var generateTable = function(values) {
    console.log("I GOT CALLED");
    if (bFormIsValid) {
        var i, j,
            strContent = "";
            strContent += "<table>";
        // i goes between the rStart and rEnd values
        for (i = values[2]; i < values[3]; i++) {
            strContent+= "<tr>";

            // j goes between the cStart and cEnd values
            for (j = values[0]; j < values[1]; j++) {
                strContent += "<td>" + (i * j) + "</td>";
            }

            strContent += "</tr>";
        }

        $("#tableArea").text(strContent);
    } else {
        return;
    }
};